<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(Let, , s start with multiple choice.)_AB7Lab Id5V1</name>
   <tag></tag>
   <elementGuidId>6a7cc6e1-e641-43de-80d4-ce7078dfcdb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i5']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.AB7Lab.Id5V1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5847932d-d9fc-4442-ada5-c83f139c1a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>35ca79fd-c0d9-4bda-97d1-00dc5d5dfc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i5&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>fb9582ec-1a10-442b-9b2d-44edff607d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames - Web Automation Test/iframe_Loading</value>
      <webElementGuid>decae07c-b2f3-46e6-9865-db4dacf76bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i5']/div[3]/div</value>
      <webElementGuid>be42f2f7-cc74-4c83-b99d-fa2f0b975082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::div[20]</value>
      <webElementGuid>0ad95704-f33b-44a3-a3ae-3a87a2e4696a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, I am the UI.Vision IDE'])[1]/preceding::div[2]</value>
      <webElementGuid>b7a37d30-0489-4a3f-b8a8-117e10d37bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am a human'])[1]/preceding::div[11]</value>
      <webElementGuid>b5a66501-a5b9-4d3c-b591-ce1f97285f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div/div[3]/div</value>
      <webElementGuid>f5e1d916-bc5c-4240-b37d-8b949fd277bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
