<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1_2</name>
   <tag></tag>
   <elementGuidId>accc74cd-a098-42bc-8a96-4da74a5e2d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frameset/frameset/frame[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>7059767b-430e-40ac-86ad-7503133e4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_3.html</value>
      <webElementGuid>61fcb646-09b4-4ba3-955f-df4700788326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>314b6e40-6a79-4959-863d-c357107eafdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame[2]</value>
      <webElementGuid>a5a3b8bd-faaa-472d-9b5f-71a19d54b592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_3.html']</value>
      <webElementGuid>bb104c80-94a7-4016-9c89-4ee735ab4216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
