<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>18961035-08a2-4479-bac2-03c07541e390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ac08adf1-3f03-49b1-a528-656d2b8da397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_1.html</value>
      <webElementGuid>b543dd77-f694-4bfd-b789-ce6af9b68f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>f33c4cd7-887f-42c2-bfdb-825c0814d9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>cabe4524-9620-46d7-b5a1-48a02546807b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_1.html']</value>
      <webElementGuid>89c0c9fd-0729-4869-8bb8-1496327dc649</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
