<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frame1_mytext1</name>
   <tag></tag>
   <elementGuidId>c68fa9e6-deab-46cd-ace2-ca7e381007e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mytext1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mytext1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b7012cf-b6a6-420a-9f26-246e8fa0022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99760764-6913-495a-b47d-d058c4021745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mytext1</value>
      <webElementGuid>4254c2d4-5580-46f2-a10c-127f3e147f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f8d0bc89-c931-42db-80a0-d56a4e154a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id1&quot;)/div[1]/input[1]</value>
      <webElementGuid>f8800732-998e-4ed0-a1b5-f09c0b2abc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames - Web Automation Test/frame</value>
      <webElementGuid>43f2305b-c876-43cb-8db8-549e4972ea43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mytext1']</value>
      <webElementGuid>36cd29a0-e780-4d4c-9979-5cc9ff909257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id1']/div/input</value>
      <webElementGuid>26369977-a5e1-4c70-b216-2fa5e8b83f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88658f24-12d9-4860-b882-0e7c67c3eb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mytext1']</value>
      <webElementGuid>a49cbbf7-b309-4d93-a07a-40df64c92554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
